import type {
  Activity,
  CompareResponse,
  EvaluationResponse,
  MockLearner,
  Placement,
  ReviewerTrace,
} from "./types";

export const confidenceChoices = [
  { value: 0.2 as const, label: "Not confident" },
  { value: 0.45 as const, label: "Somewhat confident" },
  { value: 0.7 as const, label: "Confident" },
  { value: 0.95 as const, label: "Very confident" },
];

export const demoActivities: Activity[] = [
  {
    activity_id: "vector_anchor_01",
    kind: "multiple_choice",
    eyebrow: "Prerequisite check",
    title: "Two forces act on a cart: 3 N right and 1 N left. What is the net force?",
    instructions: "Choose the best answer.",
    options: [
      { id: "A", label: "4 N right" },
      { id: "B", label: "2 N right" },
      { id: "C", label: "2 N left" },
      { id: "D", label: "0 N" },
    ],
    stage: 1,
    total_stages: 7,
  },
  {
    activity_id: "net_force_anchor_02",
    kind: "multiple_choice",
    eyebrow: "Concept check",
    title: "A cart moves at constant velocity. What must be true about its net force?",
    instructions: "Choose the best answer.",
    options: [
      { id: "A", label: "A forward net force keeps it moving." },
      { id: "B", label: "Its net force is zero." },
      { id: "C", label: "There are no forces acting on it." },
      { id: "D", label: "Its net force increases with time." },
    ],
    stage: 2,
    total_stages: 7,
  },
  {
    activity_id: "n2l_anchor_03",
    kind: "numeric",
    eyebrow: "Target check",
    title: "A 2 kg object has a net force of 6 N to the right. What is its acceleration?",
    instructions: "Enter a number. The unit is m/s².",
    unit: "m/s²",
    stage: 3,
    total_stages: 7,
  },
  {
    activity_id: "n2l_recovery_01",
    kind: "multiple_choice",
    eyebrow: "Guided recovery",
    title: "A 5 kg cart is pushed 25 N right against 10 N friction. What is its acceleration?",
    instructions: "Combine the forces before applying F = ma.",
    options: [
      { id: "A", label: "3 m/s² right" },
      { id: "B", label: "5 m/s² right" },
      { id: "C", label: "7 m/s² right" },
      { id: "D", label: "3 m/s² left" },
    ],
    stage: 4,
    total_stages: 7,
  },
];

export const guidedActivity: Activity = {
  activity_id: "n2l_probe_02",
  kind: "multiple_choice",
  eyebrow: "Misconception check",
  title: "Is a force required to keep an object moving with constant velocity in a straight line?",
  instructions: "Choose the best answer.",
  options: [
    { id: "A", label: "Yes, a constant force is needed to maintain the motion." },
    { id: "B", label: "No, no net force is required; the object continues at the same velocity." },
    { id: "C", label: "Yes, but only a very small force is required." },
    { id: "D", label: "No, but a force is required opposite to the motion." },
  ],
  stage: 2,
  total_stages: 4,
};

export const defaultPlacement: Placement = {
  selected_strategy: "Guided Solver",
  modifiers: ["balanced"],
  observed: [
    "You identified the net-force direction correctly.",
    "One structured hint helped you complete the acceleration step.",
  ],
  not_inferred: ["intelligence", "motivation", "permanent learning style"],
  certainty: "medium",
  next_evidence_needed: "Two independent problems will show when to reduce guidance.",
};

export const mockLearners: MockLearner[] = [
  {
    learner_id: "asha",
    name: "Asha",
    scenario: "Needs prerequisite repair and smaller steps before applying F = ma.",
    exam_goal: "JEE Main",
    base_mode: "Foundation First",
    modifiers: ["small chunks"],
    memory_preview: {
      summary: "Asha benefits from rebuilding net-force reasoning before moving to acceleration.",
      strengths: ["Recognises force direction", "Persists after feedback"],
      needs_practice: ["Combining opposing forces", "Selecting the correct prerequisite"],
      active_strategy: "Foundation First",
      modifiers: ["small chunks"],
      evidence_freshness: "Updated 1 day ago",
    },
  },
  {
    learner_id: "rohan",
    name: "Rohan",
    scenario: "Learns reliably from one worked example followed by fading hints.",
    exam_goal: "NEET",
    base_mode: "Guided Solver",
    modifiers: ["worked example first"],
    memory_preview: {
      summary: "Rohan is ready for guided practice with support that fades quickly.",
      strengths: ["Uses formulas accurately", "Self-corrects after one cue"],
      needs_practice: ["Independent setup"],
      active_strategy: "Guided Solver",
      modifiers: ["worked example first"],
      evidence_freshness: "Updated 2 days ago",
    },
  },
  {
    learner_id: "meera",
    name: "Meera",
    scenario: "High independent mastery; ready for transfer and compact explanations.",
    exam_goal: "JEE Advanced",
    base_mode: "Independent Challenger",
    modifiers: ["compact"],
    memory_preview: {
      summary: "Meera has stable independent evidence across recent sessions.",
      strengths: ["Multi-step force problems", "Error analysis", "Transfer"],
      needs_practice: ["Explaining assumptions precisely"],
      active_strategy: "Independent Challenger",
      modifiers: ["compact"],
      evidence_freshness: "Updated today",
    },
  },
  {
    learner_id: "kabir",
    name: "Kabir",
    scenario: "Strong mechanics basics with a recurring force-and-motion misconception.",
    exam_goal: "JEE Main",
    base_mode: "Guided Solver",
    modifiers: ["confidence check", "misconception probe"],
    memory_preview: {
      summary: "Kabir understands calculations but has repeated a constant-velocity misconception.",
      strengths: ["Net force causes acceleration", "F = ma (units and meaning)"],
      needs_practice: ["Constant velocity vs zero net force"],
      active_strategy: "Guided Solver",
      modifiers: ["confidence check", "misconception probe"],
      evidence_freshness: "Updated today",
    },
  },
  {
    learner_id: "tara",
    name: "Tara",
    scenario: "Strong mastery with underconfidence on independent work.",
    exam_goal: "Olympiad",
    base_mode: "Independent Challenger",
    modifiers: ["confidence check", "compact"],
    memory_preview: {
      summary: "Tara solves stretch items independently but underrates correct answers.",
      strengths: ["Transfer problems", "Independent reasoning"],
      needs_practice: ["Evidence-based confidence"],
      active_strategy: "Independent Challenger",
      modifiers: ["confidence check", "compact"],
      evidence_freshness: "Updated 3 days ago",
    },
  },
  {
    learner_id: "zoya",
    name: "Zoya",
    scenario: "Repeated matched evidence supports approved force diagrams.",
    exam_goal: "NEET",
    base_mode: "Guided Solver",
    modifiers: ["diagram supported"],
    memory_preview: {
      summary: "Zoya has benefited from approved diagrams across matched problems.",
      strengths: ["Diagram interpretation", "Vector direction"],
      needs_practice: ["Translating diagrams into equations"],
      active_strategy: "Guided Solver",
      modifiers: ["diagram supported"],
      evidence_freshness: "Updated 4 days ago",
    },
  },
  {
    learner_id: "dev",
    name: "Dev",
    scenario: "Contradictory evidence from a noisy session requires a careful re-check.",
    exam_goal: "JEE Main",
    base_mode: "Guided Solver",
    modifiers: ["balanced", "provisional"],
    memory_preview: {
      summary: "Dev's last session was interrupted, so the tutor will collect another clean signal.",
      strengths: ["Prior vector work"],
      needs_practice: ["Clean confirmation item"],
      active_strategy: "Guided Solver",
      modifiers: ["balanced", "provisional"],
      evidence_freshness: "Provisional",
      warning: "Recent evidence is contradictory. No durable strategy change will be made today.",
    },
  },
  {
    learner_id: "isha",
    name: "Isha",
    scenario: "Requests a topic outside the pinned verified-content catalog.",
    exam_goal: "Olympiad",
    base_mode: "Safe refusal",
    modifiers: [],
    memory_preview: {
      summary: "The requested topic is not covered by this verified demo catalog.",
      strengths: ["Curious about advanced topics"],
      needs_practice: ["Choose a supported prerequisite"],
      active_strategy: "Safe refusal",
      modifiers: [],
      evidence_freshness: "Current catalog check",
      warning: "The tutor will not invent an explanation when verified content is missing.",
    },
  },
];

export const demoCompare: CompareResponse = {
  left: {
    learner_id: "asha",
    learner_name: "Asha",
    plan: {
      plan_hash: "sha256:2c7d…9a4f",
      input_hash: "sha256:01ae…71d0",
      policy_version: "2026-08-28.2",
      catalog_version: "mechanics-2026-08-28",
      decision: { base_mode: "Foundation First", modifiers: ["small chunks"] },
      blocks: [
        { order: 1, kind: "prerequisite_check", title: "Net-force direction check", hint_limit: 1 },
        { order: 2, kind: "micro_explanation", title: "Vector sum in one step" },
        { order: 3, kind: "worked_example", title: "Resolve forces, then apply F = ma", hint_limit: 3 },
        { order: 4, kind: "guided_item", title: "On-level guided practice", hint_limit: 3 },
        { order: 5, kind: "recap", title: "Explain why forces are subtracted" },
      ],
    },
  },
  right: {
    learner_id: "meera",
    learner_name: "Meera",
    plan: {
      plan_hash: "sha256:8a1b…313c",
      input_hash: "sha256:0b3c…19fe",
      policy_version: "2026-08-28.2",
      catalog_version: "mechanics-2026-08-28",
      decision: { base_mode: "Independent Challenger", modifiers: ["compact"] },
      blocks: [
        { order: 1, kind: "concise_principle", title: "Resolve net force before F = ma" },
        { order: 2, kind: "transfer_problem", title: "Two-stage motion challenge", hint_limit: 1 },
        { order: 3, kind: "delayed_hint", title: "One hint after a complete attempt", hint_limit: 1 },
        { order: 4, kind: "error_reflection", title: "Identify the tempting assumption" },
        { order: 5, kind: "extension", title: "Predict the effect of doubled mass" },
      ],
    },
  },
  differences: [
    { dimension: "Starting point", left: "Prerequisite check", right: "Direct target principle", reason: "Net-force prerequisite evidence" },
    { dimension: "Explanation", left: "Worked, three steps", right: "Compact, one principle", reason: "Mastery and support need" },
    { dimension: "Practice", left: "Guided on-level", right: "Transfer problem", reason: "Difficulty policy" },
    { dimension: "Hints", left: "Up to three progressive hints", right: "One delayed hint", reason: "Scaffolding evidence" },
    { dimension: "Reflection", left: "Restate procedure", right: "Analyze an assumption", reason: "Lesson skeleton" },
  ],
};

export const demoEvaluation: EvaluationResponse = {
  status: "passed",
  quality_score: 94,
  gates: [
    { name: "Verified claims only", passed: true, detail: "0 unknown claims across golden cases" },
    { name: "Safe unsupported-content behavior", passed: true, detail: "Isha refused without generated physics" },
    { name: "Deterministic plans", passed: true, detail: "1 plan hash across 20 repeats per profile" },
    { name: "Memory and idempotency", passed: true, detail: "All transition and duplicate-turn assertions passed" },
    { name: "Golden policy match", passed: true, detail: "8 of 8 profiles matched exactly" },
  ],
  cases: mockLearners.map((learner, index) => ({
    learner_id: learner.learner_id,
    expected: `${learner.base_mode}${learner.modifiers.length ? ` + ${learner.modifiers.join(", ")}` : ""}`,
    actual: `${learner.base_mode}${learner.modifiers.length ? ` + ${learner.modifiers.join(", ")}` : ""}`,
    passed: true,
    plan_hash: `sha256:${["2c7d", "17ae", "8a1b", "c801", "efa0", "142b", "557d", "safe"][index]}…`,
    latency_ms: 106 + index * 13,
  })),
  honesty_notice: "These tests measure deterministic behavior on fixed mocked cases. They do not demonstrate real student learning gains.",
};

export const demoTrace: ReviewerTrace = {
  trace_id: "tr_kabir_024",
  status: "validated",
  plan_hash: "sha256:c801…45d2",
  versions: {
    policy: "2026-08-28.2",
    catalog: "mechanics-2026-08-28",
    renderer: "template-1.0",
    grader: "deterministic-1.0",
  },
  pipeline: [
    { name: "State", status: "complete" },
    { name: "Safety", status: "complete" },
    { name: "Policy", status: "complete" },
    { name: "Retrieval", status: "complete" },
    { name: "Plan", status: "complete" },
    { name: "Validation", status: "complete" },
    { name: "Memory", status: "complete" },
  ],
  evidence: [
    { observation: "Misconception appeared on two distinct items", weight: "1.00", use: "Activated probe" },
    { observation: "Recent mastery estimate 0.63", weight: "6.3 obs", use: "Kept Guided Solver" },
    { observation: "Confidence bias +0.31", weight: "9 obs", use: "Added confidence check" },
  ],
  rules: [
    { id: "P_GUIDED_DEFAULT", detail: "Mastery below challenge boundary", result: "Guided Solver" },
    { id: "MISC_PROBE_FIRST", detail: "Confirmed blocker is checked first", result: "Probe inserted at block 1" },
    { id: "CAL_OVER_01", detail: "Bias ≥ 0.20 across sessions", result: "Confidence check on" },
  ],
  state_diff: [
    { field: "newton_second_law.mastery", before: "0.61", after: "0.63" },
    { field: "policy.base_mode", before: "guided_solver", after: "guided_solver" },
    { field: "misconception.status", before: "candidate", after: "confirmed" },
  ],
  timings: [
    { phase: "State load and reduce", ms: 18 },
    { phase: "Policy and plan", ms: 7 },
    { phase: "Retrieval", ms: 10 },
    { phase: "Rendering", ms: 41 },
    { phase: "Validation", ms: 11 },
  ],
};
